# Generated by Django 5.0.3 on 2024-11-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=50)),
                ('work_type', models.CharField(choices=[('contract', 'Contract'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=30)),
            ],
        ),
    ]
