# Generated by Django 5.0.3 on 2024-11-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='position',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
