# Generated by Django 5.0.3 on 2024-11-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_employee_details_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='roles',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('hr', 'HR'), ('sales', 'Sales')], default='developer', max_length=20),
        ),
    ]
