# Generated by Django 5.0.3 on 2024-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_employee_details_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='roles',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('hr', 'HR'), ('sales', 'Sales')], max_length=20),
        ),
    ]
