# Generated by Django 5.0.3 on 2024-11-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_employee_details_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='roles',
            field=models.CharField(max_length=50),
        ),
    ]
